// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

function fileToString(url) {
  return Fs.readFileSync(url, "utf8");
}

exports.fileToString = fileToString;
/* fs Not a pure module */
